spring.application.name=ufrn

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#automatically changes java entity -> hibernate
spring.jpa.hibernate.ddl-auto=update

#shows SQL comands in intellij
spring.jpa.show-sql=true

#SQL comands formatted in console
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always

#tempo máximo que o Spring espera por uma conexão do pool (em milissegundos)
spring.datasource.hikari.connection-timeout=30000

#impede que a aplicação quebre no início se o banco estiver acordando
spring.datasource.hikari.initialization-fail-timeout=-1

gemini.api-key=${GEMINI_API_KEY}